---
abstract: 'Narada configuration plugin'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.42, CPAN::Meta::Converter version 2.133380'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Narada
provides:
  Mojolicious::Plugin::Narada:
    file: lib/Mojolicious/Plugin/Narada.pm
    version: v0.2.2
requires:
  MojoX::Log::Fast: 0
  Mojolicious: 0
  Narada: 0
  perl: 5.01
  version: 0.77
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.2.2
